spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
    #192.168.56.101 192.168.51.104
  jpa:
    show-sql: true
server:
  context-path: /sell

wechat:
  mpAppId: wx0c77ebd334a86436
  mpAppSecret: 7062222207632503d2bd55b84652a833
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://w193365j58.iok.la/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://w193365j58.iok.la
  wechatOpenAuthorize: http://w193365j58.iok.la
  sell: http://w193365j58.iok.la
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: C:\0pzb\study\logs\ #默认spring.log
#  file: C:\0pzb\study\log\logger.log
#  level: debug
