spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.56.101/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
server:
  context-path: /weixin_sell
#logging:
#  pattern:
#    console: "%d - %msg%n"
#  #path: C:\0pzb\study\logs\ #默认spring.log
#  file: C:\0pzb\study\log\logger.log
#  level: debug
